<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('km_codes', function (Blueprint $table) {
            // AI 91: verification key — 4 chars, generated by the operator
            $table->char('verification_key', 4)->nullable()->after('batch');
            // AI 92: verification code (crypto tail) — 44 chars, generated by the operator
            $table->char('verification_code', 44)->nullable()->after('verification_key');
        });
    }

    public function down(): void
    {
        Schema::table('km_codes', function (Blueprint $table) {
            $table->dropColumn(['verification_key', 'verification_code']);
        });
    }
};
